name: in_app_review
description: Flutter plugin for showing the In-App Review/System Rating pop up on Android, IOS and MacOS. Makes it easy for users to rate your app.
version: 1.0.4
homepage: https://github.com/britannio/in_app_review/tree/master/in_app_review

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  in_app_review_platform_interface: ^1.0.5
  
#dev_dependencies:
#  flutter_test:
    #sdk: flutter#
  #
  #mockito: ^4.1.3
  plugin_platform_interface: ^1.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: dev.britannio.in_app_review
        pluginClass: InAppReviewPlugin
      ios:
        pluginClass: SwiftInAppReviewPlugin
      macos:
        pluginClass: InAppReviewPlugin
